const demoAccEmail = process.env.NEXT_PUBLIC_DEMO_ACCOUNT_EMAIL ?? "demo.user@example.com";
const demoAccPassword = process.env.NEXT_PUBLIC_DEMO_ACCOUNT_PASSWORD ?? "demopass123";

const demoUserAccount = {
	name: null,
	displayName: "Demo User",
	email: demoAccEmail,
	username: "demo_user",
	emailVerified: new Date().toISOString(),
	image: null,
	password: demoAccPassword,
	banner_color: "#27AE80",
	bio: "This is a demo account used to explore the app's features.",
};

const users = [
	{
		name: null,
		displayName: "Tasha Rodriguez",
		email: "tasha_rodriguez@example.com",
		username: "tasha_rodriguez",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#964CE5",
		bio: `White owner onto knowledge other. First drug contain start almost wonder. Live bed serious theory type.`,
	},
	{
		name: null,
		displayName: "Sanya Deshmukh",
		email: "sanya_deshmukh@example.com",
		username: "sanya_deshmukh",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#1D4391",
		bio: `Party main picture suddenly drug rule. Relate head color international. Situation talk despite stage. Own available buy country store build before.`,
	},
	{
		name: null,
		displayName: "Ananya Verma",
		email: "ananya_verma@example.com",
		username: "ananya_verma",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#BF11E0",
		bio: `Per structure attorney author feeling job. Mean always beyond write. Employee toward like total now. Small citizen class morning. Others kind company likely.`,
	},
	{
		name: null,
		displayName: "Aarav Patel",
		email: "aarav_patel@example.com",
		username: "aarav_patel",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#D4247D",
		bio: `Security stock ball organization recognize civil. Pm her then nothing increase.`,
	},
	{
		name: null,
		displayName: "Theodore Mcgrath",
		email: "theodore_mcgrath@example.com",
		username: "theodore_mcgrath",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#D3CA17",
		bio: `First degree response able state more. Couple part cup few. Beyond take however ball. Son break either president stage population boy. Everything affect American race.`,
	},
	{
		name: null,
		displayName: "Elizabeth Woods",
		email: "elizabeth_woods@example.com",
		username: "elizabeth_woods",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#DA9984",
		bio: `Full per among clearly. Face house nature fall long dream answer conference. Rock few structure federal board night loss.`,
	},
	{
		name: null,
		displayName: "Peter Montgomery",
		email: "peter_montgomery@example.com",
		username: "peter_montgomery",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#D3FB25",
		bio: `Hour million large major. Institution happy write end since. Court boy state table agree moment. Budget huge debate among way. Perhaps bit learn gun still.`,
	},
	{
		name: null,
		displayName: "Nikhil Rao",
		email: "nikhil_rao@example.com",
		username: "nikhil_rao",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#23F957",
		bio: `Along chance either six success on. At be than always different American address. Former claim chance prevent why measure too.`,
	},
	{
		name: null,
		displayName: "Stephanie Sutton",
		email: "stephanie_sutton@example.com",
		username: "stephanie_sutton",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#50A313",
		bio: `Now four management energy stay significant his. Artist political camera expert stop area. Individual man tell response purpose character would.`,
	},
	{
		name: null,
		displayName: "Dana Nguyen",
		email: "dana_nguyen@example.com",
		username: "dana_nguyen",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#A15A44",
		bio: `Place full buy radio perform small camera treatment. True their race special million. Although hot he couple ground.`,
	},
	{
		name: null,
		displayName: "Priya Sharma",
		email: "priya_sharma@example.com",
		username: "priya_sharma",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#177BB6",
		bio: `Between similar safe air. Issue indicate market ten foot education good. Grow ahead girl act. Audience throw debate daughter purpose voice. Security fall ready usually.`,
	},
	{
		name: null,
		displayName: "April Snyder",
		email: "april_snyder@example.com",
		username: "april_snyder",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#7C26F1",
		bio: `Player contain year bill ok choose today. Source firm drug senior. Information animal car after back available. Federal indicate unit opportunity fear great.`,
	},
	{
		name: null,
		displayName: "Cheryl Bradley",
		email: "cheryl_bradley@example.com",
		username: "cheryl_bradley",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#6D7E2D",
		bio: `Painting child reflect up control instead company. Future model green place beat sense far.`,
	},
	{
		name: null,
		displayName: "Susan Levy",
		email: "susan_levy@example.com",
		username: "susan_levy",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#C92435",
		bio: `Three report know second government the pull. Other along society figure future. Teacher three seven attention team executive care.`,
	},
	{
		name: null,
		displayName: "Sean Green",
		email: "sean_green@example.com",
		username: "sean_green",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#B1E99E",
		bio: `Feel seat appear perform agent likely. Suffer without rather. According American per yourself their record. Cell of course its respond.`,
	},
	{
		name: null,
		displayName: "Brian Hamilton",
		email: "brian_hamilton@example.com",
		username: "brian_hamilton",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#17D857",
		bio: `Almost plan that hair sea quality. Father beautiful than seem sign third in approach. Program possible natural same issue lawyer effort.`,
	},
	{
		name: null,
		displayName: "Karan Joshi",
		email: "karan_joshi@example.com",
		username: "karan_joshi",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#94B07E",
		bio: `Eight miss couple bag thank generation. Economy rock feeling might his. Gas Republican and various authority leave right. Without leave brother bank better she.`,
	},
	{
		name: null,
		displayName: "Susan Wagner",
		email: "susan_wagner@example.com",
		username: "susan_wagner",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#D3F8A1",
		bio: `Represent since method left plant. Discussion budget situation between run. Design they young according movement.`,
	},
	{
		name: null,
		displayName: "Walter Pratt",
		email: "walter_pratt@example.com",
		username: "walter_pratt",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#E68B4A",
		bio: `Happen play speech theory choice computer. Career deal trip market. Dog car do his part.`,
	},
	{
		name: null,
		displayName: "Norma Fisher",
		email: "norma_fisher@example.com",
		username: "norma_fisher",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#8086A9",
		bio: `Page region start size. Want decade firm section economic television. General class admit of around. Character against physical agency and difficult president at.`,
	},
	{
		name: null,
		displayName: "Rohan Mehta",
		email: "rohan_mehta@example.com",
		username: "rohan_mehta",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#4738BA",
		bio: `Through move source wonder relate service. Important hope about catch. Style record bag down stock computer watch. Sea stuff no response.`,
	},
	{
		name: null,
		displayName: "Jennifer Summers",
		email: "jennifer_summers@example.com",
		username: "jennifer_summers",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#AEEDF4",
		bio: `Significant now energy. Lay return identify. Anything event yet effect quite reflect upon. Might history strong economy break word source. Only result race government trouble.`,
	},
	{
		name: null,
		displayName: "Aditya Kapoor",
		email: "aditya_kapoor@example.com",
		username: "aditya_kapoor",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#222551",
		bio: `Notice kind game act. Section could nature interest wear. Morning as police often. Place myself his itself find add sing.`,
	},
	{
		name: null,
		displayName: "Kimberly Smith",
		email: "kimberly_smith@example.com",
		username: "kimberly_smith",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#A81DE5",
		bio: `Guess we no in pass sound. Tonight gun word citizen create. Physical market room eat through ever.`,
	},
	{
		name: null,
		displayName: "Ishita Reddy",
		email: "ishita_reddy@example.com",
		username: "ishita_reddy",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#193E00",
		bio: `Action economy several hit simple personal home. Let stop camera report foreign agency list miss. Not girl above course.`,
	},
	{
		name: null,
		displayName: "Bobby Flores",
		email: "bobby_flores@example.com",
		username: "bobby_flores",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#D67071",
		bio: `Throughout treat relate respond. Role mind statement.`,
	},
	{
		name: null,
		displayName: "Meera Iyer",
		email: "meera_iyer@example.com",
		username: "meera_iyer",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#FC83EA",
		bio: `Particularly speech mission remember tree care sign. Myself star gas spend. Into good later street. Gun subject PM carry understand consumer by.`,
	},
	{
		name: null,
		displayName: "Jorge Sullivan",
		email: "jorge_sullivan@example.com",
		username: "jorge_sullivan",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#CA05FA",
		bio: `We ask benefit ago again. Pattern president add lead network the. Ball appear television so teach energy possible. Student bag grow better. Child might source.`,
	},
	{
		name: null,
		displayName: "Stephanie Collins",
		email: "stephanie_collins@example.com",
		username: "stephanie_collins",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#25786B",
		bio: `Company TV policy drug. Foreign agency when personal huge difficult player forget. Difficult there leg theory case north. Class on reach.`,
	},
	{
		name: null,
		displayName: "Michelle Kelley",
		email: "michelle_kelley@example.com",
		username: "michelle_kelley",
		emailVerified: new Date().toISOString(),
		image: null,
		banner_color: "#7651B1",
		bio: `Job trial four easy case member. Authority imagine probably whom it job. High trouble drive loss turn attorney education. Those head against particularly listen.`,
	},
];
const universalUserPassword = process.env.NEXT_PUBLIC_UNIVERSAL_USER_PASSWORD ?? "DevPass@123";

const messagesPerConversation: string[][] = [
	[
		"I've been thinking about what you said yesterday. By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
		"Do you have any recommendations for a good book or movie? I've picked up a new hobby recently and it's surprisingly relaxing. Keep me posted on how things go.",
		"Hey, just checking in to see how you're doing. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Let's chat more about this tomorrow.",
		"Hey, just checking in to see how you're doing. I'm trying to improve my routine and it's been tough staying consistent. Catch you later, take care of yourself.",
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Let's chat more about this tomorrow.",
		"Hey, just checking in to see how you're doing. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. By the way, the project deadline got moved up again. Classic! Talk soon, looking forward to hearing from you.",
	],
	[
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
		"Hey, just checking in to see how you're doing. Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
		"Do you have any recommendations for a good book or movie? The weather's been so unpredictable lately, it's messing with my plans. Let's chat more about this tomorrow.",
		"Did you hear about the latest update? I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
	],
	[
		"Let's catch up soon, maybe over coffee or a walk. I've picked up a new hobby recently and it's surprisingly relaxing. Catch you later, take care of yourself.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
		"Let's catch up soon, maybe over coffee or a walk. I'm trying to improve my routine and it's been tough staying consistent. Keep me posted on how things go.",
		"Do you have any recommendations for a good book or movie? Have you tried that new cafe down the street? The vibe is amazing. Keep me posted on how things go.",
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Talk soon, looking forward to hearing from you.",
		"Hey, just checking in to see how you're doing. I've picked up a new hobby recently and it's surprisingly relaxing. Keep me posted on how things go.",
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Catch you later, take care of yourself.",
		"Hey, just checking in to see how you're doing. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. I'm trying to improve my routine and it's been tough staying consistent. Keep me posted on how things go.",
	],
	[
		"Hey, just checking in to see how you're doing. By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Hey, just checking in to see how you're doing. The weather's been so unpredictable lately, it's messing with my plans. Let's chat more about this tomorrow.",
		"Hey, just checking in to see how you're doing. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Talk soon, looking forward to hearing from you.",
		"Did you hear about the latest update? I've picked up a new hobby recently and it's surprisingly relaxing. Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
		"I've been thinking about what you said yesterday. I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
		"Let's catch up soon, maybe over coffee or a walk. I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
	],
	[
		"Let's catch up soon, maybe over coffee or a walk. By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
		"Let's catch up soon, maybe over coffee or a walk. I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
	],
	[
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
		"Do you have any recommendations for a good book or movie? I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. I'm trying to improve my routine and it's been tough staying consistent. Keep me posted on how things go.",
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Catch you later, take care of yourself.",
		"Do you have any recommendations for a good book or movie? Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Keep me posted on how things go.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Catch you later, take care of yourself.",
	],
	[
		"I've been thinking about what you said yesterday. The weather's been so unpredictable lately, it's messing with my plans. Anyway, I'll talk to you later. Let me know what you think.",
		"Hey, just checking in to see how you're doing. I'm trying to improve my routine and it's been tough staying consistent. Keep me posted on how things go.",
		"I've been thinking about what you said yesterday. The weather's been so unpredictable lately, it's messing with my plans. Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Keep me posted on how things go.",
		"Did you hear about the latest update? The weather's been so unpredictable lately, it's messing with my plans. Let's chat more about this tomorrow.",
		"Let's catch up soon, maybe over coffee or a walk. I've picked up a new hobby recently and it's surprisingly relaxing. Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Keep me posted on how things go.",
	],
	[
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Hey, just checking in to see how you're doing. The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
		"Did you hear about the latest update? I've picked up a new hobby recently and it's surprisingly relaxing. Catch you later, take care of yourself.",
		"Do you have any recommendations for a good book or movie? The weather's been so unpredictable lately, it's messing with my plans. Anyway, I'll talk to you later. Let me know what you think.",
		"Hey, just checking in to see how you're doing. I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
		"I've been thinking about what you said yesterday. By the way, the project deadline got moved up again. Classic! Keep me posted on how things go.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
	],
	[
		"Hey, just checking in to see how you're doing. Have you tried that new cafe down the street? The vibe is amazing. Talk soon, looking forward to hearing from you.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
		"Hey, just checking in to see how you're doing. I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
		"I've been thinking about what you said yesterday. The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Keep me posted on how things go.",
		"Hey, just checking in to see how you're doing. I've picked up a new hobby recently and it's surprisingly relaxing. Catch you later, take care of yourself.",
		"Let's catch up soon, maybe over coffee or a walk. I've picked up a new hobby recently and it's surprisingly relaxing. Talk soon, looking forward to hearing from you.",
		"Hey, just checking in to see how you're doing. I'm trying to improve my routine and it's been tough staying consistent. Catch you later, take care of yourself.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Catch you later, take care of yourself.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
	],
	[
		"I've been thinking about what you said yesterday. By the way, the project deadline got moved up again. Classic! Talk soon, looking forward to hearing from you.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
		"Do you have any recommendations for a good book or movie? I've picked up a new hobby recently and it's surprisingly relaxing. Keep me posted on how things go.",
		"Hey, just checking in to see how you're doing. I've picked up a new hobby recently and it's surprisingly relaxing. Talk soon, looking forward to hearing from you.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Hey, just checking in to see how you're doing. By the way, the project deadline got moved up again. Classic! Catch you later, take care of yourself.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
	],
	[
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Catch you later, take care of yourself.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
		"Did you hear about the latest update? The weather's been so unpredictable lately, it's messing with my plans. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Keep me posted on how things go.",
		"Did you hear about the latest update? I'm trying to improve my routine and it's been tough staying consistent. Let's chat more about this tomorrow.",
	],
	[
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
		"Did you hear about the latest update? I'm trying to improve my routine and it's been tough staying consistent. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. I'm trying to improve my routine and it's been tough staying consistent. Catch you later, take care of yourself.",
	],
	[
		"Let's catch up soon, maybe over coffee or a walk. I've picked up a new hobby recently and it's surprisingly relaxing. Talk soon, looking forward to hearing from you.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. The weather's been so unpredictable lately, it's messing with my plans. Catch you later, take care of yourself.",
		"Hey, just checking in to see how you're doing. The weather's been so unpredictable lately, it's messing with my plans. Catch you later, take care of yourself.",
		"Did you hear about the latest update? I'm trying to improve my routine and it's been tough staying consistent. Catch you later, take care of yourself.",
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
	],
	[
		"Hey, just checking in to see how you're doing. I've picked up a new hobby recently and it's surprisingly relaxing. Talk soon, looking forward to hearing from you.",
		"Hey, just checking in to see how you're doing. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
		"Hey, just checking in to see how you're doing. The weather's been so unpredictable lately, it's messing with my plans. Anyway, I'll talk to you later. Let me know what you think.",
	],
	[
		"Do you have any recommendations for a good book or movie? Have you tried that new cafe down the street? The vibe is amazing. Keep me posted on how things go.",
		"Let's catch up soon, maybe over coffee or a walk. I'm trying to improve my routine and it's been tough staying consistent. Keep me posted on how things go.",
		"Do you have any recommendations for a good book or movie? I've picked up a new hobby recently and it's surprisingly relaxing. Keep me posted on how things go.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
	],
	[
		"Did you hear about the latest update? I'm trying to improve my routine and it's been tough staying consistent. Keep me posted on how things go.",
		"Do you have any recommendations for a good book or movie? The weather's been so unpredictable lately, it's messing with my plans. Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Talk soon, looking forward to hearing from you.",
		"I've been thinking about what you said yesterday. By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? I've picked up a new hobby recently and it's surprisingly relaxing. Keep me posted on how things go.",
	],
	[
		"Do you have any recommendations for a good book or movie? Have you tried that new cafe down the street? The vibe is amazing. Talk soon, looking forward to hearing from you.",
		"Did you hear about the latest update? I'm trying to improve my routine and it's been tough staying consistent. Keep me posted on how things go.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Catch you later, take care of yourself.",
		"Hey, just checking in to see how you're doing. The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
	],
	[
		"Let's catch up soon, maybe over coffee or a walk. By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Catch you later, take care of yourself.",
		"I've been thinking about what you said yesterday. I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Keep me posted on how things go.",
		"Did you hear about the latest update? The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
	],
	[
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Catch you later, take care of yourself.",
		"Did you hear about the latest update? I've picked up a new hobby recently and it's surprisingly relaxing. Catch you later, take care of yourself.",
		"Let's catch up soon, maybe over coffee or a walk. By the way, the project deadline got moved up again. Classic! Talk soon, looking forward to hearing from you.",
		"Do you have any recommendations for a good book or movie? Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Catch you later, take care of yourself.",
	],
	[
		"Hey, just checking in to see how you're doing. I've picked up a new hobby recently and it's surprisingly relaxing. Keep me posted on how things go.",
		"Let's catch up soon, maybe over coffee or a walk. By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Keep me posted on how things go.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. By the way, the project deadline got moved up again. Classic! Keep me posted on how things go.",
		"Did you hear about the latest update? I've picked up a new hobby recently and it's surprisingly relaxing. Catch you later, take care of yourself.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
	],
	[
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Let's chat more about this tomorrow.",
		"Did you hear about the latest update? I've picked up a new hobby recently and it's surprisingly relaxing. Anyway, I'll talk to you later. Let me know what you think.",
		"Hey, just checking in to see how you're doing. I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
		"Hey, just checking in to see how you're doing. I'm trying to improve my routine and it's been tough staying consistent. Let's chat more about this tomorrow.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
	],
	[
		"Did you hear about the latest update? I've picked up a new hobby recently and it's surprisingly relaxing. Talk soon, looking forward to hearing from you.",
		"Do you have any recommendations for a good book or movie? The weather's been so unpredictable lately, it's messing with my plans. Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? I'm trying to improve my routine and it's been tough staying consistent. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. I'm trying to improve my routine and it's been tough staying consistent. Catch you later, take care of yourself.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Talk soon, looking forward to hearing from you.",
		"I've been thinking about what you said yesterday. I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Anyway, I'll talk to you later. Let me know what you think.",
		"I've been thinking about what you said yesterday. I'm trying to improve my routine and it's been tough staying consistent. Let's chat more about this tomorrow.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Talk soon, looking forward to hearing from you.",
	],
	[
		"Did you hear about the latest update? I've picked up a new hobby recently and it's surprisingly relaxing. Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
		"Let's catch up soon, maybe over coffee or a walk. I'm trying to improve my routine and it's been tough staying consistent. Catch you later, take care of yourself.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Keep me posted on how things go.",
		"Did you hear about the latest update? I've picked up a new hobby recently and it's surprisingly relaxing. Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? I've picked up a new hobby recently and it's surprisingly relaxing. Talk soon, looking forward to hearing from you.",
		"Hey, just checking in to see how you're doing. I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
		"Hey, just checking in to see how you're doing. The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
	],
	[
		"Do you have any recommendations for a good book or movie? The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
		"Hey, just checking in to see how you're doing. The weather's been so unpredictable lately, it's messing with my plans. Catch you later, take care of yourself.",
		"Hey, just checking in to see how you're doing. I've picked up a new hobby recently and it's surprisingly relaxing. Talk soon, looking forward to hearing from you.",
		"Did you hear about the latest update? The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
		"Did you hear about the latest update? I've picked up a new hobby recently and it's surprisingly relaxing. Catch you later, take care of yourself.",
		"I've been thinking about what you said yesterday. The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
		"Hey, just checking in to see how you're doing. I've picked up a new hobby recently and it's surprisingly relaxing. Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Keep me posted on how things go.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
	],
	[
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? The weather's been so unpredictable lately, it's messing with my plans. Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
		"Hey, just checking in to see how you're doing. The weather's been so unpredictable lately, it's messing with my plans. Let's chat more about this tomorrow.",
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Catch you later, take care of yourself.",
		"I've been thinking about what you said yesterday. By the way, the project deadline got moved up again. Classic! Anyway, I'll talk to you later. Let me know what you think.",
		"Hey, just checking in to see how you're doing. By the way, the project deadline got moved up again. Classic! Talk soon, looking forward to hearing from you.",
	],
	[
		"I've been thinking about what you said yesterday. I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Keep me posted on how things go.",
		"I've been thinking about what you said yesterday. The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
		"Hey, just checking in to see how you're doing. The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
		"Let's catch up soon, maybe over coffee or a walk. By the way, the project deadline got moved up again. Classic! Keep me posted on how things go.",
		"Did you hear about the latest update? The weather's been so unpredictable lately, it's messing with my plans. Catch you later, take care of yourself.",
		"Hey, just checking in to see how you're doing. I've picked up a new hobby recently and it's surprisingly relaxing. Talk soon, looking forward to hearing from you.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Talk soon, looking forward to hearing from you.",
		"Hey, just checking in to see how you're doing. I'm trying to improve my routine and it's been tough staying consistent. Talk soon, looking forward to hearing from you.",
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Talk soon, looking forward to hearing from you.",
	],
	[
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Keep me posted on how things go.",
		"Let's catch up soon, maybe over coffee or a walk. I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Keep me posted on how things go.",
		"Did you hear about the latest update? The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Keep me posted on how things go.",
		"Did you hear about the latest update? The weather's been so unpredictable lately, it's messing with my plans. Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Anyway, I'll talk to you later. Let me know what you think.",
		"Do you have any recommendations for a good book or movie? Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
	],
	[
		"Do you have any recommendations for a good book or movie? By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
		"Hey, just checking in to see how you're doing. By the way, the project deadline got moved up again. Classic! Talk soon, looking forward to hearing from you.",
		"I've been thinking about what you said yesterday. By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
		"Hey, just checking in to see how you're doing. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Catch you later, take care of yourself.",
		"Do you have any recommendations for a good book or movie? The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
	],
	[
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Talk soon, looking forward to hearing from you.",
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
		"Hey, just checking in to see how you're doing. By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
		"Let's catch up soon, maybe over coffee or a walk. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
		"Let's catch up soon, maybe over coffee or a walk. I've picked up a new hobby recently and it's surprisingly relaxing. Anyway, I'll talk to you later. Let me know what you think.",
		"Did you hear about the latest update? I'm trying to improve my routine and it's been tough staying consistent. Anyway, I'll talk to you later. Let me know what you think.",
		"I've been thinking about what you said yesterday. I've picked up a new hobby recently and it's surprisingly relaxing. Let's chat more about this tomorrow.",
	],
	[
		"Did you hear about the latest update? By the way, the project deadline got moved up again. Classic! Let's chat more about this tomorrow.",
		"I've been thinking about what you said yesterday. By the way, the project deadline got moved up again. Classic! Keep me posted on how things go.",
		"Did you hear about the latest update? Have you tried that new cafe down the street? The vibe is amazing. Talk soon, looking forward to hearing from you.",
		"I've been thinking about what you said yesterday. Have you tried that new cafe down the street? The vibe is amazing. Catch you later, take care of yourself.",
		"Do you have any recommendations for a good book or movie? Have you tried that new cafe down the street? The vibe is amazing. Let's chat more about this tomorrow.",
		"Do you have any recommendations for a good book or movie? The weather's been so unpredictable lately, it's messing with my plans. Talk soon, looking forward to hearing from you.",
		"Let's catch up soon, maybe over coffee or a walk. The weather's been so unpredictable lately, it's messing with my plans. Keep me posted on how things go.",
		"Let's catch up soon, maybe over coffee or a walk. Have you tried that new cafe down the street? The vibe is amazing. Anyway, I'll talk to you later. Let me know what you think.",
	],
];

export { demoUserAccount, users, universalUserPassword, messagesPerConversation };
