const users = [
	{
		name: null,
		displayName: "Sophia Garcia",
		email: "sophia.garcia@example.com",
		username: "sophia.g",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "James Rodriguez",
		email: "james.rodriguez@example.com",
		username: "james.r",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Mia Hernandez",
		email: "mia.hernandez@example.com",
		username: "mia.h",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Elijah White",
		email: "elijah.white@example.com",
		username: "elijah.w",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Amelia Martinez",
		email: "amelia.martinez@example.com",
		username: "amelia.m",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Lucas Johnson",
		email: "lucas.johnson@example.com",
		username: "lucas.j",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Aiden Lee",
		email: "aiden.lee@example.com",
		username: "aiden.l",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Isabella Clark",
		email: "isabella.clark@example.com",
		username: "isabella.c",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Mason Lewis",
		email: "mason.lewis@example.com",
		username: "mason.l",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Mila Walker",
		email: "mila.walker@example.com",
		username: "mila.w",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Ethan Hall",
		email: "ethan.hall@example.com",
		username: "ethan.h",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Luna Young",
		email: "luna.young@example.com",
		username: "luna.y",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Oliver King",
		email: "oliver.king@example.com",
		username: "oliver.k",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Harper Wright",
		email: "harper.wright@example.com",
		username: "harper.w",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Jackson Perez",
		email: "jackson.perez@example.com",
		username: "jackson.p",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Evelyn Allen",
		email: "evelyn.allen@example.com",
		username: "evelyn.a",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Sebastian Scott",
		email: "sebastian.scott@example.com",
		username: "sebastian.s",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Aria Adams",
		email: "aria.adams@example.com",
		username: "aria.a",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Henry Nelson",
		email: "henry.nelson@example.com",
		username: "henry.n",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Charlotte Carter",
		email: "charlotte.carter@example.com",
		username: "charlotte.c",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Jack Mitchell",
		email: "jack.mitchell@example.com",
		username: "jack.m",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Scarlett Ramirez",
		email: "scarlett.ramirez@example.com",
		username: "scarlett.r",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Leo Murphy",
		email: "leo.murphy@example.com",
		username: "leo.m",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Emily Brooks",
		email: "emily.brooks@example.com",
		username: "emily.b",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Luke Reed",
		email: "luke.reed@example.com",
		username: "luke.r",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Avery Turner",
		email: "avery.turner@example.com",
		username: "avery.t",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Grace Anderson",
		email: "grace.anderson@example.com",
		username: "grace.a",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Matthew Ward",
		email: "matthew.ward@example.com",
		username: "matthew.w",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Victoria Rivera",
		email: "victoria.rivera@example.com",
		username: "victoria.r",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Daniel Morris",
		email: "daniel.morris@example.com",
		username: "daniel.m",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
	{
		name: null,
		displayName: "Layla Parker",
		email: "layla.parker@example.com",
		username: "layla.p",
		emailVerified: new Date().toISOString(),
		password: "$2a$10$j6VbIP2Zhl6MX.gHu4mZceUcPghs6triU.ooUFnx2n.Qv3720eOLO",
		image: null,
		avatar: null,
		banner_color: "#27AE80",
		bio: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	},
];

export { users };
