export const MAX_INPUT_CONTAINER_SIZE = 320;
export const INPUT_CONTAINER_SPACEY = 12;
export const MAX_INPUT_SIZE = MAX_INPUT_CONTAINER_SIZE - INPUT_CONTAINER_SPACEY * 2;
export const MAX_MESSAGE_CHAR_LENGTH = 500;
